name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        version: [ '8.0', '8.1', '8.2' ]

    name: Test PHP ${{ matrix.version }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.version }}

    - name: Install Follow the Money package
      run: |
        git submodule init
        git submodule update

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.version }}-

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --no-interaction

    - name: Run test suite
      run: composer run-script test
