name: Run Static Analysis

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run-static-analysis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        version: [ '8.0' ]

    name: Run Static Analysis

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.version }}-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-interaction

      - name: Run static analysis
        run: composer run psalm